// <auto-generated />
namespace BMIapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateTablePatientBMI_addBMIColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTablePatientBMI_addBMIColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201804080827089_updateTablePatientBMI_addBMIColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
